Feature/helper functions
ohmediaorg/backend-bundle pull request #1
Opened 2024-04-29 21:22 UTC by SeanPeterson

## Info
Twig functions for common bad elements used throughout modules.

2024-04-29 23:28 UTC, justin-oh commented on src/Twig/BadgeExtension.php
We'll need a function for all 8 variations: https://getbootstrap.com/docs/5.3/components/badge/#background-colors

2024-04-29 23:31 UTC, justin-oh requested changes
Note about adding more badge functions.

Also, everything for Symfony needs to be ran through php-cs-fixer. Noticed some deviations with the string concatenation.

2024-04-29 23:56 UTC, justin-oh reviewed
Sorry, I'm thinking this should go into the bootstrap bundle, in which case it should be prefixed like everything else in that bundle. We're implementing it as is in [the documentation](https://getbootstrap.com/docs/5.3/components/badge/#background-colors), if we ignore the pill effect. (I don't foresee a reason to support both badge styles.)

I think I will eventually update the prefix from `bootstrap_` to `bs_` to shorten it. These functions are used across several bundles so it's not a simple update.

2024-04-30 20:11 UTC, SeanPeterson commented
> the documentation

Now that you say that, I can't get string concatination auto-formatting to work. I think it should turn `>'.$message.'</span>'` into `>' . $message . '</span>'`?



I have the executable set to `~/ohdev/tools/php-cs-fixer/vendor/bin/php-cs-fixer`
Config set to `.php-cs-fixer.php;.php-cs-fixer.dist.php;.php_cs;.php_cs.dist`
and `  "php-cs-fixer.rules": "@PSR12",`

2024-04-30 20:14 UTC, SeanPeterson commented
fat finger close it - though it sounds like this may go into the boostrap bundle anyways

2024-04-30 20:49 UTC, justin-oh commented
@SeanPeterson Concatenation formatting removes space before and after the `.`.

The rules should be `@Symfony` instead of `@PSR12`.

2024-05-01 20:53 UTC, closed without merging